# Config file: hugo.toml

publishDir = "output"

disableKinds = ["taxonomy", "sitemap"]

cleanDestinationDir = true

timeout = "300s"

[outputs]
  home = ["HTML"]
  
[params]
   pathtoapi = "http://discovery1.dlib.nyu.edu/solr/viewer/select?indent=on&q=*:*&fq=sm_collection_code:palante&wt=json&rows=1000"
  # pathtoapi = "http://discovery1.dlib.nyu.edu/solr/viewer/select?indent=on&q=*:*&fq=bundle:dlts_book&fq=sm_collection_partner_code:tamwag&wt=json&rows=1000"
  
  
