# Config file: hugo.toml

publishDir = "output"

disableKinds = ["taxonomy", "sitemap"]

[outputs]
  home = ["HTML"]
  
[params]
  pathtoapi = "http://discovery1.dlib.nyu.edu/solr/viewer/select?indent=on&q=*:*&fq=sm_collection_code:fawf&wt=json&rows=300"
  
  